[package]
name = "portfolio-solver-framework"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
command-group = "5.0.1"
ctrlc = "3.5.1"
kill_tree = { version = "0.2.4", features = ["tokio"] }
futures = "0.3.31"
tokio = "1.48.0"
libc = "0.2.178"
nix = {version = "0.30.1", features = ["signal", "process"]}
