name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  fast-checks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Check formatting
      run: cargo fmt --all -- --check
    - name: Linting
      run: cargo clippy --verbose --locked -- -D warnings
    - name: Install cargo-audit
      run: cargo install cargo-audit --locked
    - name: Audit
      run: cargo audit

  unit-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v6
      with:
        target: ci
        load: true
        tags: framework:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Unit tests
      run: docker run -t framework:latest cargo test --release --verbose --locked

  integration-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build integration Docker image
      uses: docker/build-push-action@v6
      with:
        target: ci-integration
        load: true
        tags: framework:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Integration tests
      run: docker run -t framework:latest cargo test --tests --release --verbose --locked
