name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check formatting
      run: cargo fmt --all -- --check
    - name: Linting
      run: cargo clippy --verbose --locked -- -D warnings

    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        target: builder
        push: true
        load: true
        tags: framework:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    # - name: Build
    #   run: docker run -t framework:latest cargo build --verbose --locked
    - name: Tests
      run: docker run -t framework:latest cargo test --verbose --locked
    - name: Audit
      run: docker run -t framework:latest cargo audit
