name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  MAKE_JOBS: 2 # When building the Dockerfile, use 2 make jobs

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check formatting
      run: cargo fmt --all -- --check

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Linting
      run: cargo clippy --verbose --locked -- -D warnings

  audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install cargo-audit
      run: cargo install cargo-audit --locked
    - name: Audit
      run: cargo audit

  unit-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v6
      with:
        target: ci
        load: true
        tags: jobork/framework:latest
        cache-from: type=registry,ref=jobork/framework:buildcache
        cache-to: type=registry,ref=jobork/framework:buildcache,mode=max

    - name: Unit tests
      run: docker run -t jobork/framework:latest cargo test --release --verbose --locked

  integration-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build integration Docker image
      uses: docker/build-push-action@v6
      with:
        target: ci-integration
        load: true
        tags: jobork/framework:latest
        cache-from: type=registry,ref=jobork/framework:buildcache
        cache-to: type=registry,ref=jobork/framework:buildcache,mode=max

    - name: Integration tests
      run: docker run -t jobork/framework:latest cargo test --tests --release --verbose --locked
